const  cardoftheday = [
  "You are exactly where you’re meant to be. Trust the timing.",
  "Be here now. The present is more powerful than you think.",
  "Let go of the need to know. Trust the unfolding.",
  "What’s meant for you will never miss you.",
  "Slow down. Life isn't a race.",
  "Your pace is perfect.",
  "Breathe. You’re doing better than you think.",
  "In stillness, answers arrive.",
  "You’re not behind. You’re on your path.",
  "Trust your roots. Grow slow, grow strong.",
  "Pause. There’s wisdom in silence.",
  "You already hold the answer.",
  "Clarity comes when the mind is quiet.",
  "Ask less why — and more what now.",
  "Every experience carries a lesson.",
  "What you seek is seeking you.",
  "Let curiosity guide you.",
  "Listen deeply. Not just to reply, but to understand.",
  "Growth begins at the edge of comfort.",
  "When nothing is certain, everything is possible.",
  "Speak to yourself like you would to a friend.",
  "Self-love is your foundation.",
  "Be kinder to yourself today.",
  "Rest is not a reward. It’s a right.",
  "Your worth is not measured in productivity.",
  "Don’t shrink to fit. You’re meant to shine.",
  "The way you speak to yourself matters.",
  "It’s okay to feel it all.",
  "You don’t have to do it all to be loved.",
  "You are more capable than you realize.",
  "Feel the fear — and do it anyway.",
  "You’ve survived 100% of your hardest days.",
  "Keep showing up. That’s enough.",
  "Doubt is part of the process — not the end.",
  "The comeback is always stronger.",
  "Rise gently, but rise.",
  "There’s power in persistence.",
  "You are not the storm — you are the sky.",
  "Even the smallest step forward matters.",
  "Let it go. Make space for something new.",
  "You are allowed to outgrow versions of yourself.",
  "Transformation begins with truth.",
  "New beginnings often disguise themselves as painful endings.",
  "Embrace the unknown. That’s where magic lives.",
  "Change is not chaos. It’s creation.",
  "Be open to becoming someone you've never been.",
  "It’s never too late to begin again.",
  "Growth is messy — and worth it.",
  "The cocoon is tight, but the wings are coming",
  "The sun always rises — so will you.",
  "Light exists even on the cloudy days.",
  "Keep going — something beautiful is forming.",
  "Hope is a quiet strength.",
  "Look for the light — or become it.",
  "Joy is still possible here.",
  "Your story isn't over yet.",
  "The cracks are how the light gets in.",
  "You are the light someone else needs today.",
  "Rain nourishes what sunshine cannot.",
  "Move with purpose, not pressure.",
  "Small steps. Big impact.",
  "Say no to protect your yes.",
  "Energy flows where intention goes.",
  "Progress, not perfection.",
  "Direction is more important than speed.",
  "Choose what aligns, not what impresses.",
  "Make time for what truly matters.",
  "Focus on what you can control.",
  "Your “why” is your anchor.",
  "Stay true to who you are becoming.",
  "You don’t need to explain your path.",
  "Real is better than perfect.",
  "Honor what feels right — even if others don’t understand.",
  "Your vibe attracts your tribe.",
  "Be the most you version of you.",
  "Don’t dim to fit in.",
  "Your uniqueness is your superpower.",
  "Authenticity is magnetic.",
  "Live life aligned, not approved.",
  "What you appreciate, appreciates.",
  "Notice the little joys today.",
  "Gratitude changes everything.",
  "Count blessings, not burdens.",
  "There’s beauty in ordinary moments.",
  "You have more than you think.",
  "Thank yourself for making it this far.",
  "Every breath is a gift.",
  "Even now, there's something to smile about.",
  "Gratitude is the heart’s memory.",
  "Follow the quiet pull of your intuition.",
  "Magic happens when you believe it can.",
  "Let your inner voice be louder than your doubt.",
  "Synchronicities are signs — pay attention.",
  "The universe is always listening.",
  "You are deeply connected to something greater.",
  "Miracles live in moments we overlook.",
  "Notice what keeps returning to your heart.",
  "Trust the whispers, not just the noise.",
  "You’re guided. You’re protected. You’re loved."
]


export default cardoftheday;